server:
  port: 8090

spring:
  application:
    name: scrooge-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/scrooge
    username: "postgres_usr"
    password: "postgres_pwd"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      pool-name: HikariPool
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
    open-in-view: false
    show-sql: false

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: public
    enabled: true

scrooge:
  infrastructure:
    web:
      public-urls:
        - "/swagger-ui/**"
        - "/swagger-resources/**"
        - "/v3/api-docs/**"
        - "/debug-tools/errors/**"
      trusted-issuers:
        - "https://sso.scrooge.io/realms/scrooge-realm"

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO