server:
  port: 8090

spring:
  application:
    name: scrooge-backend

scrooge:
  infrastructure:
    web:
      public-urls:
        - "/public"
        - "/static"
      trusted-issuers:
        - "https://sso.scrooge.lan/realms/scrooge-realm"

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO