server:
  port: 8090

spring:
  application:
    name: scrooge-backend

scrooge:
  infrastructure:
    web:
      public-urls:
        - "/swagger-ui/**"
        - "/swagger-resources/**"
        - "/v3/api-docs/**"
      trusted-issuers:
        - "https://sso.scrooge.io/realms/scrooge-realm"

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO