###
GET {{host}}/debug-tools/me
Authorization: Bearer {{$auth.token("token")}}


###
GET {{host}}/1.0/bank-accounts
Authorization: Bearer {{$auth.token("token")}}
Content-Type: application/json


###
POST {{host}}/1.0/bank-accounts
Authorization: Bearer {{$auth.token("token")}}
Content-Type: application/json

{
  "mnemonicName": "IlMioPrimoContoCorrente"
}